### ISSUE TITLE
Fiji crashes with error regarding logging

### ISSUE THREAD

**Issue by haesleinhuepf** [scijava/scijava-log-slf4j#3]
Hey guys,

after the recent update of Fiji, one of my Fiji installations didn't startup anymore. Running it as debug.exe allowed me to see what goes wrong: 

'''
[DEBUG] SingleInstance: starting server
[DEBUG] publish(
        context = org.scijava.Context@4d94bd68
        consumed = false,null,null), called from non-EDT Thread:null
[DEBUG] SingleInstance: server ready
[DEBUG] sendArguments: return false
[DEBUG] Received command line arguments:
[DEBUG] Discovered user interface: net.imagej.legacy.ui.LegacyUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.sdi.SwingSDIUI
[DEBUG] Discovered user interface: org.scijava.ui.awt.AWTUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.mdi.SwingMdiUI
[DEBUG] Discovered user interface: org.scijava.ui.headless.HeadlessUI
[DEBUG] Launching user interface: net.imagej.legacy.ui.LegacyUI
Error while executing the main() method of class 'net.imagej.Main':
java.lang.NoClassDefFoundError: org/scijava/log/LogListener
        at net.imagej.legacy.ui.LegacyUI.createConsole(LegacyUI.java:152)
        at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:144)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:156)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:141)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:103)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
Caused by: java.lang.ClassNotFoundException: org.scijava.log.LogListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
'''

Is this error related to the new logging stuff? Is there anything users can do apart form reinstalling Fiji?

(OS was Windows 10 64 bit)

Thanks!
Robert

**Comment by ctrueden** [comment]
Whoa, strange! The class `org.scijava.log.LogListener` is part of scijava-common since 2.66.0.
```
$ javap -classpath jars/scijava-common-2.69.0.jar org.scijava.log.LogListener
Compiled from "LogListener.java"
public interface org.scijava.log.LogListener {
  public abstract void messageLogged(org.scijava.log.LogMessage);
}
```
What version of `jars/scijava-common.jar` is present in this installation?

Is it possible the scijava-common JAR file is somehow corrupted? It should be 843244 bytes.

**Comment by haesleinhuepf** [comment]
Hey Curtis,

it's indeed strange: The jars folder contains scijava-common-2.65.0.jar last modified 2017-12-29. Many other jar files were last modified 2017-08-06. I guess I downloaded that Fiji in August. But it was updated very often.

Under which circumstances would the updater download such an "old" jar file? May it have something to do with the updater being updated?

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Ah, I think I found the issue: My IDE installed old jar files to this Fiji installation, not the updater! My fault. But thanks for your support! I'll close this issue.
